#!/usr/bin/env python3
"""Generate the Cloudflare Pages Function that blocks withdrawn /works/* URLs.

Cloudflare Pages can keep serving a per-hostname "preservation" copy when the
current deployment has no asset for a path. Zone purges do not clear it, which
is why fathers.saneapps.com returned 200 for held works while the deployment
URL returned 404. This Function runs before the asset server for /works/* and
returns a real 404 unless the slug is in the current live allowlist.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

FUNCTION_TEMPLATE = """\
/** Generated by scripts/generate_works_gate.py — do not edit by hand. */
const LIVE = new Set({live_json});

const NOT_FOUND_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Page unavailable</title>
</head>
<body>
<section>
<h1>Page unavailable</h1>
<p>This page is not in the current library.</p>
<p><a href="/works/">Browse works</a> or <a href="/topics/">browse topics</a>.</p>
</section>
</body>
</html>
`;

function pathSegments(params) {{
  const raw = params.path;
  if (raw == null || raw === "") return [];
  return Array.isArray(raw) ? raw : [raw];
}}

export async function onRequest(context) {{
  const segments = pathSegments(context.params);
  if (segments.length === 0) {{
    return context.env.ASSETS.fetch(context.request);
  }}
  const slug = segments[0];
  if (LIVE.has(slug)) {{
    return context.env.ASSETS.fetch(context.request);
  }}
  return new Response(NOT_FOUND_HTML, {{
    status: 404,
    headers: {{
      "content-type": "text/html; charset=utf-8",
      "cache-control": "private, no-store",
      "x-robots-tag": "noindex",
    }},
  }});
}}
"""

ROUTES_JSON = {
    "version": 1,
    "include": ["/works/*"],
    "exclude": [],
}


def live_slugs_from_works_dir(works_dir: Path) -> list[str]:
    if not works_dir.is_dir():
        raise SystemExit(f"BLOCKED: works dir missing: {works_dir}")
    slugs = sorted(
        p.name
        for p in works_dir.iterdir()
        if p.is_dir() and (p / "index.html").is_file() and SLUG_RE.fullmatch(p.name)
    )
    if not slugs:
        raise SystemExit(f"BLOCKED: no live work slugs under {works_dir}")
    return slugs


def write_gate(functions_dir: Path, slugs: list[str]) -> Path:
    target = functions_dir / "works" / "[[path]].js"
    target.parent.mkdir(parents=True, exist_ok=True)
    live_json = json.dumps(slugs, separators=(",", ":"))
    target.write_text(FUNCTION_TEMPLATE.format(live_json=live_json), encoding="utf-8")
    return target


def write_routes(stage_dir: Path) -> Path:
    path = stage_dir / "_routes.json"
    path.write_text(json.dumps(ROUTES_JSON, indent=2) + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--works-dir",
        type=Path,
        default=None,
        help="Directory of live /works/<slug>/ folders (default: <stage>/works or dist/works)",
    )
    parser.add_argument(
        "--stage",
        type=Path,
        default=None,
        help="Pages upload directory; writes _routes.json here when set",
    )
    parser.add_argument(
        "--functions-dir",
        type=Path,
        default=ROOT / "functions",
        help="Pages Functions directory (default: repo functions/)",
    )
    parser.add_argument(
        "--print-slugs",
        action="store_true",
        help="Include slug list in the receipt JSON",
    )
    args = parser.parse_args()

    works_dir = args.works_dir
    if works_dir is None:
        if args.stage is not None:
            works_dir = args.stage / "works"
        else:
            works_dir = ROOT / "dist" / "works"

    slugs = live_slugs_from_works_dir(works_dir)
    gate_path = write_gate(args.functions_dir, slugs)
    routes = write_routes(args.stage) if args.stage is not None else None
    receipt = {
        "live_works": len(slugs),
        "function": str(gate_path),
        "routes": str(routes) if routes else None,
    }
    if args.print_slugs:
        receipt["slugs"] = slugs
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
